### PR TITLE
Linux-specific: workaround of clipboard issue with Ctrl+C+C

### LINKED ISSUE #650: Ctrl+C+C  doesn't show popup in qt5 apps
Ctrl+C+C  doesn't show popup in qt5 apps and works just fine in gtk apps .
Changing the shortcut to someting else like CTRL+E+E works just fine .
have this  problem in multiple linux distros.

### LINKED ISSUE #858: ctrl+c+c popup doesn't work in evince
It works in chrome and firefox, however doesn't work in evince while reading pdf, :(

### LINKED ISSUE #1420: ctrl+c+c popup doesn't work on Ubuntu 21.10 with firefox, evince, sublime text
ctrl+c+c clipboard popup doesn't work on Ubuntu 21.10 (Gnome Shell 40.5) with firefox, evince, sublime text,... but works with chromium, chrome, VS code,...

### PR DESCRIPTION
**Pull request by wisherhxl**
Resolves #1420, Resolves #650, Resolves #858. 

New PR of #1487 with the suggested solution.

### CODE REVIEW

File: mainwindow.cc [hunk 1]
```diff
@@ -3105,7 +3105,12 @@ void MainWindow::hotKeyActivated( int hk )
     toggleMainWindow();
   else
   if ( scanPopup.get() )
+#ifdef HAVE_X11
+    // workaround of clipboard issue with Ctrl+C+C
```
Comment (vedgy) [inline mainwindow.cc:3109]: The comment is a bit too short. Could you explain the worked-around issue in more detail?

**Review by vedgy — CHANGES_REQUESTED** [review]
I suggest referencing the fixed issues in the commit message, not only in the PR description. That way the context would be easier to find for future developers.

Also please prefix the commit message with `Linux-specific: ` (see recent commits).

I am going to test this PR locally to check for regressions.

**Comment by vedgy** [comment]
Please squash all commits into one and force-push.

**Comment by wisherhxl** [comment]
@vedgy Thank you for your patience. Hopefully, it's all done right this time.

**Review by vedgy — CHANGES_REQUESTED** [review]
@wisherhxl, for some reason, you silently ignore some of my suggestions in this and previous PR.

So again: I suggest referencing the fixed issues in the commit message body, not only in the PR description. That way the context would be easier to find for future developers. They won't have to look for the related PR first, but could navigate to the issues directly from git log.

Also please use `Fixes`/`fixes` or `Closes`/`closes` keyword instead of `Resolves` as the latter has never been used in GoldenDict before.

In case you are unfamiliar with git commit message best practices: add one empty line after the current commit message subject, then in the next line reference the issues:

```
Linux-specific: ...

Closes #1420, closes #650, ...
```

Just tested the fix briefly on my system where Ctrl+C+C has worked perfectly in all applications. Haven't noticed any regressions. I think the 10 ms delay is small enough to be pretty safe regression-wise.

File: mainwindow.cc [hunk 2]
```diff
@@ -3105,7 +3105,13 @@ void MainWindow::hotKeyActivated( int hk )
     toggleMainWindow();
   else
   if ( scanPopup.get() )
+#ifdef HAVE_X11
+    // call scanPopup directly may cause clipboard conflicts with other Qt programs
+    // on Linux and make popup failed, wait a little while to fix it.
```
[the remark this answers is not in the document]
Comment (wisherhxl) [reply mainwindow.cc]: > Just tested the fix briefly on my system where Ctrl+C+C has worked perfectly in all applications. Haven't noticed any regressions. I think the 10 ms delay is small enough to be pretty safe regression-wise.

The reason I overthought this issue before was because I was afraid that the time would vary dramatically in different computers, especially old computers without SDD. But it looks like 10ms is basically enough. As my oldest computer is only 5 years old, so I cannot say that all systems are applicable. Anyway, it should solve most problems.

[the remark this answers is not in the document]
Comment (wisherhxl) [reply mainwindow.cc]: > for some reason, you silently ignore some of my suggestions in this and previous PR.
> 
> So again: I suggest referencing the fixed issues in the commit message body, not only in the PR description. That way the context would be easier to find for future developers. They won't have to look for the related PR first, but could navigate to the issues directly from git log.

Sorry for that, I hope I finally did it right this time. It's hard to do something not familiar with, but I will try my best. Thank you again.

File: mainwindow.cc [hunk 3]
```diff
@@ -3105,7 +3105,17 @@ void MainWindow::hotKeyActivated( int hk )
     toggleMainWindow();
   else
   if ( scanPopup.get() )
+#ifdef HAVE_X11
```
Comment (vedgy) [inline mainwindow.cc:3108]: The `if` block is no longer one-line, but much longer. Please add `{` above this line and `}` under `#endif` to improve readability and prevent future mistakes.

**Review by vedgy — CHANGES_REQUESTED** [review]
> Sorry for that, I hope I finally did it right this time. It's hard to do something not familiar with, but I will try my best. Thank you again.

Almost there :)
Please use "closes" consistently in the commit message (instead of "close" in one place).

Also rebase on top of the current master and force-push.

File: mainwindow.cc [hunk 4]
```diff
@@ -3105,7 +3105,19 @@ void MainWindow::hotKeyActivated( int hk )
...
+    // on some GNU/Linux systems, GoldenDict appears to handle Ctrl+C+C before the
+    // active application finishes handling Ctrl+C. As a result, GoldenDict finds
+    // the clipboard empty, silently cancels the translation request, and users report
+    // that Ctrl+C+C is broken in these apps. Slightly delay handling the clipboard
+    // hotkey to give the active application more time and thus work around the issue.
+    QTimer::singleShot( 10, scanPopup.get(), SLOT( translateWordFromClipboard() ) );
+  }
+#else
     scanPopup->translateWordFromClipboard();
+#endif
```
Comment (vedgy) [inline mainwindow.cc:3120]: The `}` should be here - under `#endif`. Otherwise it looks misleading!

**Review by vedgy — APPROVED** [review]
Looks good to me. @Abs62, could you please review and merge this?

**Comment by commandgjj** [comment]
Glade to see this issue closed finally, really appreciate you guys:)
